version: '3.8'

services:
  backend:
    build:
      context: ./back
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./front:/app

networks:
  default:
    driver: bridge
